### ISSUE TITLE
After change location in one window change label on other

### ISSUE THREAD

**Issue by somoant** [hhoao/app_tabs#12]
If I have two windows of Files opened with the same folder: 
![Screenshot from 2024-01-10 09-08-16](https://github.com/hhoao/app_tabs/assets/3972183/3e04630f-3e2a-457e-bfae-880398a20781)

and then i click on second window and change location (Downloads), location text on first tab will change too although location stay (Home)
![Screenshot from 2024-01-10 09-11-20](https://github.com/hhoao/app_tabs/assets/3972183/f1860b11-0d9d-481a-b56b-50ec97672f07)

**Comment by hhoao** [comment]
What is the version?

**Comment by hhoao** [comment]
I have found it and I will fix it right away.

**Comment by hhoao** [comment]
I found that the last version I briefly fixed this problem and submitted it to the extension website, but it has not passed the review for a month, if you want to use it in advance, you can clone it first.
