### ISSUE TITLE
Panel tab is not drawn properly

### ISSUE THREAD

**Issue by 4fort** [hhoao/app_tabs#19]
![image](https://github.com/user-attachments/assets/80338d71-94e4-4eb5-b39b-2dcc4fd0dead)
I think it is better to draw/render the tab button like how other extension does it (e.g. App Menu is back).  

![image](https://github.com/user-attachments/assets/c0f99d41-612c-42e2-98e8-dc02bda8070f)
The way this extension does it is really not the way, like how the tabs don't render properly when opening multiple windows of the same app.

**Comment by hhoao** [comment]
I'm a little confused about what you're trying to say，is the TAB not centered vertically?

**Comment by 4fort** [comment]
Yes, I've tried display: flex and align-items: center with no luck. Maybe if you render the TAB like how other extension does it it would be more dynamic and native to gnome itself

**Comment by hhoao** [comment]
There is no such problem on my device. Can you check whether the branch "fix_46_1.0.x_margin" can be used normally?
