### ISSUE TITLE
Text cut when using thin panel bar

### ISSUE THREAD

**Issue by 0Raik** [hhoao/app_tabs#5]
![Screenshot from 2023-11-10 16-19-45](https://github.com/hhoao/app_tabs/assets/5239948/46771cd5-1700-484c-aec0-bd6c1c8f1888)
Having no options to change text results in text not shown completely if using a thin panel bar. Some extensions change the panel bar like Thin panel or Just Perfection.

This extension has a great oportunity to explode as Gnome 45 removed the window title and this could be an amazing replacement for that missing feature. Some settings would make wonders to the extension like text size, tab size, etc.

Thanks for the time and great work for the extension. Have a great day.

**Comment by hhoao** [comment]
@0Raik  Upgrade to new version and configure it, thanks!
